
# fly.toml app configuration file generated for post2place on 2025-05-20T10:16:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'test-fly'
primary_region = 'fra'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 5500
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '8gb'
  cpu_kind = 'shared'
  cpus = 4
